name: Build and Deploy

on:
  push:
    branches:
      - master  # Ensure your branch is actually named 'master'

permissions:
  contents: read
  packages: write  # Needed for pushing images to DockerHub

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Linux, X64]  # Match the exact labels of your self-hosted runner
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disable shallow clones for better relevancy
        
      - name: Docker build and push
        run: |
          docker build -t swiggy-clone .
          docker tag swiggy-clone emerald1213/swiggy-clone:latest
          echo "${{ secrets.Dockerhub_token }}" | docker login -u "${{ secrets.Dockerhub_username }}" --password-stdin
          docker push emerald1213/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]  # Match exact runner labels
    steps:
      - name: Pull Docker image
        run: docker pull emerald1213/swiggy-clone:latest

      - name: Stop and Remove Existing Container
        run: |
          docker stop swiggy-clone1 || true
          docker rm swiggy-clone1 || true

      - name: Deploy to container
        run: docker run -d --name swiggy-clone1 -p 3000:3000 emerald1213/swiggy-clone:latest
