name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Docker build and push
        run: |
          docker build -t swiggy-clone .
          docker tag swiggy-clone emerald1213/swiggy-clone:latest
          echo "${{ secrets.Dockerhub_token }}" | docker login --username "${{ secrets.Dockerhub_username }}" --password-stdin
          docker push emerald1213/swiggy-clone:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kubeconfig
        run: aws eks --region ap-south-1 update-kubeconfig --name cicd

      - name: Deploy to Kubernetes
        run: sudo kubectl apply -f deployment-service.yml
